name: Docker Container Action

on:
  push:
    branches:
      - main  # 當推送到主分支時觸發行動

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest allinone image
        run: docker pull youshandefeiyang/allinone:latest

      - name: Run allinone container
        run: |
          docker run --name allinone-container youshandefeiyang/allinone:34555
          
      - name: Copy tv.m3u file
        run: |
          docker cp allinone-container:/app/tv.m3u ./tv.m3u  # 根據實際路徑更新

      - name: Cleanup
        run: |
          docker stop allinone-container
          docker rm allinone-container
