name: Docker Container Action

on:
  push:
    branches:
      - main  # 當推送到主分支時觸發行動

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest allinone image
        run: docker pull youshandefeiyang/allinone:latest

      - name: Run allinone container
        run: |
          docker run --name allinone -d -p 35455:35455 youshandefeiyang/allinone
        
      - name: Copy tv.m3u file
        run: |
          docker cp allinone-container:/path/to/tv.m3u ./tv.m3u  # 修改路徑為實際的 tv.m3u 存放位置

      - name: Cleanup
        run: |
          docker stop allinone-container
          docker rm allinone-container
