name: Docker Container Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull Docker image
        run: |
          docker pull youshandefeiyang/allinone:latest

      - name: Run Docker container
        run: |
          docker run --name allinone_container -d youshandefeiyang/allinone:latest

      - name: Wait for the container to generate tv.m3u
        run: |
          sleep 60  # 等待一段时间以确保文件生成，可以根据需要调整时间

      - name: Copy tv.m3u from the container
        run: |
          docker cp allinone_container:/path/to/tv.m3u ./tv.m3u  # 替换为实际路径

      - name: Stop and remove the container
        run: |
          docker stop allinone_container
          docker rm allinone_container

      - name: Upload tv.m3u as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tv.m3u
          path: ./tv.m3u
